-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
ROLLBACK;

BEGIN;

/*
CREATE DATABASE student_project
  WITH OWNER = postgres
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.UTF-8'
  LC_CTYPE   = 'en_US.UTF-8'
  TEMPLATE   = template0;
*/
 
CREATE SCHEMA IF NOT EXISTS student_project ;


-- -----------------------------------------------------
-- Table `student_project`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.asignatura
(
    id_asignatura serial NOT NULL,
    nombre_asignatura VARCHAR(100),
    CONSTRAINT asignatura_pkey PRIMARY KEY (id_asignatura)
);

COMMENT ON TABLE student_project.asignatura
    IS 'Tabla con las asignaturas impartidas.';

-- -----------------------------------------------------
-- Table `student_project`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.tutor
(
    correo_electronico VARCHAR(100) PRIMARY KEY,
    nombre VARCHAR(100),
    apellidos VARCHAR(100),
    genero VARCHAR(100),
    telefono VARCHAR(25) UNIQUE,
    "NIF" VARCHAR(100) NOT NULL,
    direccion_facturacion VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);


COMMENT ON TABLE student_project.tutor
    IS 'Información referente a los tutores legales de los alumnos.';

-- -----------------------------------------------------
-- Table `student_project`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.curso
(
    id_curso serial NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_curso)
);

COMMENT ON TABLE student_project.curso
    IS 'Cursos de los alumnos';

-- -----------------------------------------------------
-- Table `student_project`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.ciudad
(
    id_ciudad serial NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_ciudad)
);

COMMENT ON TABLE student_project.ciudad
    IS 'Ciudades donde se imparten clases.';

-- -----------------------------------------------------
-- Table `student_project`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.ubicacion
(
    id_ubicacion serial PRIMARY KEY,
--	Direccion TEXT NOT NULL,
    Distrito VARCHAR(100),
    Barrio VARCHAR(100),
    Codigo_postal VARCHAR(100),
	id_ciudad INT NOT NULL REFERENCES student_project.ciudad(id_ciudad)
    ON DELETE RESTRICT
    ON UPDATE CASCADE		
);

COMMENT ON TABLE student_project.ubicacion
    IS 'Información referente a los alumnos';	


-- -----------------------------------------------------
-- Table `student_project`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.alumno
(
    id_alumno serial PRIMARY KEY,
    nombre VARCHAR(100),
    apellidos VARCHAR(100),
    direccion VARCHAR(100),
    NIF VARCHAR(100) NOT NULL,
    telefono VARCHAR(25) UNIQUE,
    genero VARCHAR(100),

        correo_tutor VARCHAR(100) NOT NULL REFERENCES student_project.tutor(correo_electronico)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
        id_curso INT NOT NULL REFERENCES student_project.curso(id_curso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
	id_ubicacion INT NOT NULL REFERENCES student_project.ubicacion(id_ubicacion)
    ON DELETE RESTRICT
    ON UPDATE CASCADE	
);

COMMENT ON TABLE student_project.alumno
    IS 'Información referente a los alumnos';


-- -----------------------------------------------------
-- Table `student_project`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.profesor
(
    id_profesor serial PRIMARY KEY,
    nombre VARCHAR(100),
    apellidos VARCHAR(100),
    genero VARCHAR(100),
    telefono VARCHAR(25) UNIQUE,
    correo_electronico VARCHAR(100) UNIQUE NOT NULL,
    "NIF" VARCHAR(100) NOT NULL,
    direccion_facturacion VARCHAR(100) NOT NULL,
    "IBAN" VARCHAR(100) NOT NULL,
    carrera VARCHAR(100) NOT NULL,
    curso VARCHAR(100) NOT NULL,
    experiencia TEXT NOT NULL,
    password VARCHAR(255) NOT NULL
);

COMMENT ON TABLE student_project.profesor
    IS 'Información de profesores.';

-- -----------------------------------------------------
-- Table `student_project`.`oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.oferta
(
    id_oferta serial PRIMARY KEY,
    fecha_oferta date NOT NULL,
    disponibilidad VARCHAR(100) NOT NULL,
    estado VARCHAR(100),
    numero_horas numeric NOT NULL,
    modalidad VARCHAR(100) NOT NULL,
    beneficio_sp numeric NOT NULL,
    ganancia_profesor numeric NOT NULL,
    precio_alumno numeric NOT NULL,
    precio_profesor numeric NOT NULL,

	id_alumno INT NOT NULL REFERENCES student_project.alumno(id_alumno)
    ON DELETE RESTRICT
    ON UPDATE CASCADE	
);

COMMENT ON TABLE student_project.oferta
    IS 'Solicitudes de clase creadas por los tutores.';

-- -----------------------------------------------------
-- Table `student_project`.`oferta_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.oferta_asignatura
(
    id_oferta INT NOT NULL,
    id_asignatura INT NOT NULL,
    PRIMARY KEY (id_oferta, id_asignatura),

	FOREIGN KEY(id_asignatura)  REFERENCES student_project.asignatura(id_asignatura)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,		
	FOREIGN KEY(id_oferta)  REFERENCES student_project.oferta(id_oferta)
    ON DELETE RESTRICT
    ON UPDATE CASCADE		
);

-- -----------------------------------------------------
-- Table `student_project`.`puja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.puja
(
    id_puja serial PRIMARY KEY,
    fecha_puja date NOT NULL,
    estado_puja VARCHAR(100),
	id_profesor INT NOT NULL REFERENCES student_project.profesor(id_profesor)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
	id_oferta INT NOT NULL REFERENCES student_project.oferta(id_oferta)
    ON DELETE RESTRICT
    ON UPDATE CASCADE	
);

COMMENT ON TABLE student_project.puja
    IS 'Referente a las pujas que se hacen.';


-- -----------------------------------------------------
-- Table `student_project`.`puja_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.puja_asignatura
(
    id_puja INT NOT NULL,
    id_asignatura INT  NOT NULL,
    precio numeric NOT NULL,
    PRIMARY KEY (id_puja, id_asignatura),
	FOREIGN KEY (id_asignatura) REFERENCES student_project.asignatura(id_asignatura)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,		
	FOREIGN KEY (id_puja) REFERENCES student_project.puja(id_puja)
    ON DELETE RESTRICT
    ON UPDATE CASCADE		
);


-- -----------------------------------------------------
-- Table `student_project`.`clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS student_project.clase
(
    id_clase serial PRIMARY KEY,
    fecha_clase date NOT NULL,
    hora_clase time without time zone NOT NULL,
    modalidad_clase VARCHAR(100) NOT NULL,
    precio_total_clase numeric NOT NULL,
    beneficio_clase numeric NOT NULL,
    duracion_clase numeric NOT NULL,
    fecha_registro_clase date NOT NULL,

        id_asignatura INT NOT NULL REFERENCES student_project.asignatura(id_asignatura)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
        id_ubicacion INT NOT NULL REFERENCES student_project.ubicacion(id_ubicacion)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
        id_profesor INT NOT NULL REFERENCES student_project.profesor(id_profesor)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
        id_alumno INT NOT NULL REFERENCES student_project.alumno(id_alumno)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

COMMENT ON TABLE student_project.clase
    IS 'Información referente a las clases.';
